app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
homepage:
    path:   /
    defaults:  { _controller: AppBundle\Controller\UserController:index }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

logout:
    path: /logout
    defaults: { _controller: AppBundle:Security:logout }

edit:
    path:     /edit
    controller: AppBundle\Controller\UserController::editAction
    requirements:
        id: '\d+'

delete:
    path:     /delete
    controller: AppBundle\Controller\UserController::deleteAction
    requirements:
        id: '\d+'

getOptions:
    path:     /getOptions
    controller: AppBundle\Controller\UserController::getOptionsLocationAction

checkUserPropertyExists:
    path:     /checkUserPropertyExists
    controller: AppBundle\Controller\UserController::propertyExist
    requirements:
        field: 'identification'
        q: '\d+'