# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt    

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    # providers:
    #     in_memory:
    #         memory: ~
    providers:
        app_user_provider:
            entity:
                class: AppBundle\Entity\User
                property: email
            # entity: { class: AppBundle\Entity\User, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            # provider: app_user_provider
    #         guard:
    #             authenticators:
    #                 - app.form_login_authenticator
    #         form_login:
    #           login_path: /login
    #           check_path: /login
    #           always_use_default_target_path: true
    #         logout:
    #           path: logout
    #           target: /

    # access_control:
    #     - {path: login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #     - {path: ^/, roles: IS_AUTHENTICATED_FULLY}              
