AppBundle\Entity\User:
    type: entity
    table: user_app
    uniqueConstraints:
        UNIQ_22781144E7927C74:
            columns:
                - email
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        firstName:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
            column: last_name
        phone:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        isActive:
            type: boolean
            nullable: false
            column: is_active
        email:
            type: string
            nullable: false
            length: 254
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 64
            options:
                fixed: false
        identification:
            type: string
            nullable: false
            length: 254
            options:
                fixed: false
    lifecycleCallbacks: {  }
