<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVv5f6eu\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVv5f6eu/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVv5f6eu.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVv5f6eu\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerVv5f6eu\appDevDebugProjectContainer([
    'container.build_hash' => 'Vv5f6eu',
    'container.build_id' => '0fa0f89d',
    'container.build_time' => 1558417283,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVv5f6eu');
