<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container9vqouax\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container9vqouax/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container9vqouax.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container9vqouax\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container9vqouax\appDevDebugProjectContainer([
    'container.build_hash' => '9vqouax',
    'container.build_id' => 'faf2d464',
    'container.build_time' => 1558452482,
], __DIR__.\DIRECTORY_SEPARATOR.'Container9vqouax');
